export const UDP_PACKET_TYPE_DEFAULT = "UDP_PACKET_TYPE_DEFAULT";

export const UDP_PACKET_TYPE_DNS = "UDP_PACKET_TYPE_DNS"; // 53
export const UDP_PACKET_MULTI_CAST_DOMAIN_NAME_SYSTEM = "UDP_PACKET_MULTI_CAST_DOMAIN_NAME_SYSTEM"; // 5353
export const UDP_PACKET_SIMPLE_SEARCH_DISCOVERY_PROTOCOL = "UDP_PACKET_MULTI_CAST_DOMAIN_NAME_SYSTEM"; // 1900
export const UDP_PACKET_QUIC_PROTOCOL = "UDP_PACKET_QUIC_PROTOCOL"; // 443
export const UDP_PACKET_LOCAL_LINK_MULTICAST_NAME_RESOLUTION = "UDP_PACKET_LOCAL_LINK_MULTICAST_NAME_RESOLUTION"; // 5355
export const UDP_PACKET_NETBIOS_NAME_SERVICE = "UDP_PACKET_NETBIOS_NAME_SERVICE"; // 137
export const UDP_PACKET_DROPBOX_LAN_SYNC = "UDP_PACKET_DROPBOX_LAN_SYNC"; // 17500
export const UDP_PACKET_SPOTIFY = "UDP_PACKET_SPOTIFY"; // 4070

export const UDP_PORTS = [
    {type: UDP_PACKET_TYPE_DNS, shortName: "DNS", longName: 'DNS', port: 53},
    {type: UDP_PACKET_MULTI_CAST_DOMAIN_NAME_SYSTEM, shortName: "MDNS", longName: 'MDNS', port: 5353},
    {type: UDP_PACKET_SIMPLE_SEARCH_DISCOVERY_PROTOCOL, shortName: "SSDP", longName: 'SSDP', port: 1900},
    {type: UDP_PACKET_QUIC_PROTOCOL, shortName: "QUIC", longName: 'QUIC', port: 443},
    {type: UDP_PACKET_LOCAL_LINK_MULTICAST_NAME_RESOLUTION, shortName: "LLMNR", longName: 'LLMNR', port: 5355},
    {type: UDP_PACKET_NETBIOS_NAME_SERVICE, shortName: "NBNS", longName: 'NBNS', port: 137},
    {type: UDP_PACKET_DROPBOX_LAN_SYNC, shortName: "Dropbox", longName: 'Dropbox', port: 17500},
    {type: UDP_PACKET_SPOTIFY, shortName: "Spotify", longName: 'Spotify', port: 4070},
]
